# Generated by Django 5.2.17 on 2026-09-30 08:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(default='cricket', editable=False, max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('opponent', models.CharField(max_length=80)),
                ('venue', models.CharField(blank=True, max_length=80)),
                ('fmt', models.CharField(choices=[('T10', 'T10'), ('T20', 'T20'), ('ODI', 'ODI'), ('TEST', 'Test'), ('OTH', 'Other')], default='T20', max_length=4, verbose_name='Format')),
                ('result', models.CharField(choices=[('W', 'Won'), ('L', 'Lost'), ('D', 'Draw / Tie'), ('NR', 'No result')], default='W', max_length=2)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MatchPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batted', models.BooleanField(default=True)),
                ('runs', models.PositiveSmallIntegerField(default=0)),
                ('balls_faced', models.PositiveSmallIntegerField(default=0)),
                ('fours', models.PositiveSmallIntegerField(default=0)),
                ('sixes', models.PositiveSmallIntegerField(default=0)),
                ('not_out', models.BooleanField(default=False)),
                ('balls_bowled', models.PositiveSmallIntegerField(default=0)),
                ('runs_conceded', models.PositiveSmallIntegerField(default=0)),
                ('wickets', models.PositiveSmallIntegerField(default=0)),
                ('maidens', models.PositiveSmallIntegerField(default=0)),
                ('dot_balls', models.PositiveSmallIntegerField(default=0)),
                ('catches', models.PositiveSmallIntegerField(default=0)),
                ('run_outs', models.PositiveSmallIntegerField(default=0)),
                ('stumpings', models.PositiveSmallIntegerField(default=0)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='core.match')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('sport', models.CharField(default='cricket', editable=False, max_length=20)),
                ('role', models.CharField(choices=[('bat', 'Batter'), ('bowl', 'Bowler'), ('ar', 'All-rounder'), ('wk', 'Wicket-keeper')], default='ar', max_length=5)),
                ('batting_style', models.CharField(choices=[('R', 'Right-hand'), ('L', 'Left-hand')], default='R', max_length=1)),
                ('bowling_style', models.CharField(blank=True, help_text='e.g. Right-arm medium', max_length=60)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.profile'),
        ),
    ]
