# Generated by Django 6.0.7 on 2026-10-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_cutout',
            field=models.ImageField(blank=True, upload_to='profile_cutouts/'),
        ),
    ]
